/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  jakubmol
 * Created: 20-Jan-2021
 */

INSERT INTO APPOINTMENT (HOST_ID, PATIENT_ID, COMMENTS, APPOINTMENT_START, APPOINTMENT_DURATION, CHARGE, IS_COMPLETE, IS_PAID) VALUES (1, 3, 'Some sort of a toothache', '2021-01-04', '00:00:10', 20, 0, 0);
INSERT INTO APPOINTMENT (HOST_ID, PATIENT_ID, COMMENTS, APPOINTMENT_START, APPOINTMENT_DURATION, CHARGE, IS_COMPLETE, IS_PAID) VALUES (1, 4, 'Elbow pains', '2021-01-20', '00:00:30', 15, 0, 0);
INSERT INTO APPOINTMENT (HOST_ID, PATIENT_ID, COMMENTS, APPOINTMENT_START, APPOINTMENT_DURATION, CHARGE, IS_COMPLETE, IS_PAID) VALUES (2, 5, 'Perscription change', '2021-01-02', '00:00:20', 5, 0, 0);
INSERT INTO APPOINTMENT (HOST_ID, PATIENT_ID, COMMENTS, APPOINTMENT_START, APPOINTMENT_DURATION, CHARGE, IS_COMPLETE, IS_PAID) VALUES (1, 6, 'Frequent headaches', '2021-01-27', '00:00:10', 15, 0, 0);
INSERT INTO APPOINTMENT (HOST_ID, PATIENT_ID, COMMENTS, APPOINTMENT_START, APPOINTMENT_DURATION, CHARGE, IS_COMPLETE, IS_PAID) VALUES (1, 7, 'Allergy issues', '2021-01-10', '00:00:10', 10, 0, 0);
INSERT INTO APPOINTMENT (HOST_ID, PATIENT_ID, COMMENTS, APPOINTMENT_START, APPOINTMENT_DURATION, CHARGE, IS_COMPLETE, IS_PAID) VALUES (1, 8, 'Check up', '2021-01-15', '00:00:30', 20, 0, 0);
INSERT INTO APPOINTMENT (HOST_ID, PATIENT_ID, COMMENTS, APPOINTMENT_START, APPOINTMENT_DURATION, CHARGE, IS_COMPLETE, IS_PAID) VALUES (1, 9, 'Hearing loss', '2021-01-19', '00:00:50', 15, 0, 0);
INSERT INTO APPOINTMENT (HOST_ID, PATIENT_ID, COMMENTS, APPOINTMENT_START, APPOINTMENT_DURATION, CHARGE, IS_COMPLETE, IS_PAID) VALUES (1, 3, 'Blood test', '2021-01-01', '00:00:10', 10, 0, 0);
INSERT INTO APPOINTMENT (HOST_ID, PATIENT_ID, COMMENTS, APPOINTMENT_START, APPOINTMENT_DURATION, CHARGE, IS_COMPLETE, IS_PAID) VALUES (1, 4, 'Foot pain', '2021-01-28', '00:00:40', 15, 0, 0);
INSERT INTO APPOINTMENT (HOST_ID, PATIENT_ID, COMMENTS, APPOINTMENT_START, APPOINTMENT_DURATION, CHARGE, IS_COMPLETE, IS_PAID) VALUES (1, 5, 'Chesty cough', '2021-01-12', '00:00:10', 15, 0, 0);